#Description: Middleware sdmmc host usdhc; user_visible: True
include_guard(GLOBAL)
message("middleware_sdmmc_host_usdhc component is included.")

target_sources(${MCUX_SDK_PROJECT_NAME} PRIVATE
)

target_include_directories(${MCUX_SDK_PROJECT_NAME} PUBLIC
    ${CMAKE_CURRENT_LIST_DIR}/host/usdhc
)

#OR Logic component
if(CONFIG_USE_middleware_sdmmc_host_usdhc_freertos_MIMXRT1042) 
    include(middleware_sdmmc_host_usdhc_freertos_MIMXRT1042)
endif()
if(CONFIG_USE_middleware_sdmmc_host_usdhc_freertos_MIMXRT1176_cm7) 
    include(middleware_sdmmc_host_usdhc_freertos_MIMXRT1176_cm7)
endif()
if(CONFIG_USE_middleware_sdmmc_host_usdhc_freertos_MIMXRT1176_cm4) 
    include(middleware_sdmmc_host_usdhc_freertos_MIMXRT1176_cm4)
endif()
if(CONFIG_USE_middleware_sdmmc_host_usdhc_polling_MIMXRT1042) 
    include(middleware_sdmmc_host_usdhc_polling_MIMXRT1042)
endif()
if(CONFIG_USE_middleware_sdmmc_host_usdhc_interrupt_MIMXRT1176_cm4) 
    include(middleware_sdmmc_host_usdhc_interrupt_MIMXRT1176_cm4)
endif()
if(CONFIG_USE_middleware_sdmmc_host_usdhc_polling_MIMXRT1176_cm4) 
    include(middleware_sdmmc_host_usdhc_polling_MIMXRT1176_cm4)
endif()
if(CONFIG_USE_middleware_sdmmc_host_usdhc_interrupt_MIMXRT1062) 
    include(middleware_sdmmc_host_usdhc_interrupt_MIMXRT1062)
endif()
if(CONFIG_USE_middleware_sdmmc_host_usdhc_polling_MIMXRT595S_cm33) 
    include(middleware_sdmmc_host_usdhc_polling_MIMXRT595S_cm33)
endif()
if(CONFIG_USE_middleware_sdmmc_host_usdhc_azurertos) 
    include(middleware_sdmmc_host_usdhc_azurertos)
endif()
if(CONFIG_USE_middleware_sdmmc_host_usdhc_polling_MIMXRT1062) 
    include(middleware_sdmmc_host_usdhc_polling_MIMXRT1062)
endif()
if(CONFIG_USE_middleware_sdmmc_host_usdhc_freertos_MIMXRT595S_cm33) 
    include(middleware_sdmmc_host_usdhc_freertos_MIMXRT595S_cm33)
endif()
if(CONFIG_USE_middleware_sdmmc_host_usdhc_interrupt_MIMXRT1042) 
    include(middleware_sdmmc_host_usdhc_interrupt_MIMXRT1042)
endif()
if(CONFIG_USE_middleware_sdmmc_host_usdhc_interrupt_MIMXRT1176_cm7) 
    include(middleware_sdmmc_host_usdhc_interrupt_MIMXRT1176_cm7)
endif()
if(CONFIG_USE_middleware_sdmmc_host_usdhc_polling_MIMXRT1176_cm7) 
    include(middleware_sdmmc_host_usdhc_polling_MIMXRT1176_cm7)
endif()
if(CONFIG_USE_middleware_sdmmc_host_usdhc_interrupt_MIMXRT595S_cm33) 
    include(middleware_sdmmc_host_usdhc_interrupt_MIMXRT595S_cm33)
endif()
if(CONFIG_USE_middleware_sdmmc_host_usdhc_freertos_MIMXRT1062) 
    include(middleware_sdmmc_host_usdhc_freertos_MIMXRT1062)
endif()

