#Description: SDMMC sdio stack; user_visible: True
include_guard(GLOBAL)
message("middleware_sdmmc_sdio component is included.")

target_sources(${MCUX_SDK_PROJECT_NAME} PRIVATE
    ${CMAKE_CURRENT_LIST_DIR}/sdio/fsl_sdio.c
)

target_include_directories(${MCUX_SDK_PROJECT_NAME} PUBLIC
    ${CMAKE_CURRENT_LIST_DIR}/sdio
)

#OR Logic component
if(${MCUX_DEVICE} STREQUAL "MIMXRT1166_cm7")
    include(middleware_sdmmc_host_usdhc)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1052")
    include(middleware_sdmmc_host_usdhc)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT633S_cm33")
    include(middleware_sdmmc_host_usdhc)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1064")
    include(middleware_sdmmc_host_usdhc)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54607")
    include(middleware_sdmmc_host_sdif)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54S016")
    include(middleware_sdmmc_host_sdif)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54606")
    include(middleware_sdmmc_host_sdif)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54616")
    include(middleware_sdmmc_host_sdif)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54016")
    include(middleware_sdmmc_host_sdif)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54018")
    include(middleware_sdmmc_host_sdif)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54628")
    include(middleware_sdmmc_host_sdif)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1173_cm4")
    include(middleware_sdmmc_host_usdhc)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1173_cm7")
    include(middleware_sdmmc_host_usdhc)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54605")
    include(middleware_sdmmc_host_sdif)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1051")
    include(middleware_sdmmc_host_usdhc)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54618")
    include(middleware_sdmmc_host_sdif)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1021")
    include(middleware_sdmmc_host_usdhc)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT555S_cm33")
    include(middleware_sdmmc_host_usdhc)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54018M")
    include(middleware_sdmmc_host_sdif)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1062")
    include(middleware_sdmmc_host_usdhc)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54S018")
    include(middleware_sdmmc_host_sdif)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1042")
    include(middleware_sdmmc_host_usdhc)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1176_cm4")
    include(middleware_sdmmc_host_usdhc)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1176_cm7")
    include(middleware_sdmmc_host_usdhc)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1175_cm4")
    include(middleware_sdmmc_host_usdhc)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1175_cm7")
    include(middleware_sdmmc_host_usdhc)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54S018M")
    include(middleware_sdmmc_host_sdif)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1061")
    include(middleware_sdmmc_host_usdhc)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1165_cm7")
    include(middleware_sdmmc_host_usdhc)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54S005")
    include(middleware_sdmmc_host_sdif)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54005")
    include(middleware_sdmmc_host_sdif)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT533S_cm33")
    include(middleware_sdmmc_host_usdhc)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54608")
    include(middleware_sdmmc_host_sdif)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT685S_cm33")
    include(middleware_sdmmc_host_usdhc)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT595S_cm33")
    include(middleware_sdmmc_host_usdhc)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1166_cm4")
    include(middleware_sdmmc_host_usdhc)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1165_cm4")
    include(middleware_sdmmc_host_usdhc)
endif()

include(middleware_sdmmc_common)
